### PR TITLE
AMD [NOT MERGE!] 

### PR DESCRIPTION
**Pull request by crystian**
Just for comparative branches, **I am never going to merge it.**
It breaks installation on Windows with this error:

image

If you are a Linux user with AMD card, you can use this branch rather than the main

Powered by: @PurplefinNeptuna

### CODE REVIEW

**Comment by PurplefinNeptuna** [comment]
@crystian ah, I forgot to test this on windows, my bad.
can you try install pyrsmi and running it on your windows?
```py
from pyrsmi import rocml
rocml.smi_initialize()
```
if an error raised, at least we can just use that library with try catch and have amd supported without breaking windows install

**Comment by PurplefinNeptuna** [comment]
pyrsmi seems ok in windows (tested both amd and nvidia gpu), it throws error but we can catch it

**Comment by crystian** [comment]
@PurplefinNeptuna can you make a PR with the changes on branch AMD? (on your fork)
but if it needs to install `pyamdgpuinfo`, it will break on installation not in execution (where we can catch it)

**Comment by PurplefinNeptuna** [comment]
@crystian pyamdgpuinfo isn't needed, I was changed to it before because temperature reading (pyrsmi dont have it).

**Comment by crystian** [comment]
but I see this library in the PR, please update it and I'll check it

**Pull request closed without merging**
